### ISSUE TITLE
Pinia 升级导致无法运行

### ISSUE THREAD

**Issue by Hbisedm** [Ares-Chang/uni-vitesse#10]
运行环境是要求pnpm什么版本么，安装依赖有问题

<img width="564" alt="image" src="https://github.com/Ares-Chang/uni-vitesse/assets/51397088/ec999c6d-7be9-459c-a3c4-8518f3214c8b">

**Comment by Ares-Chang** [comment]
你是不是升级了 pinia  版本，推荐降级到 2.0.36 以下试试。

如果还是不行的话，建议多给点代码块提示，一个截图不是很好找问题。

如果能提供一个 [最小实现](https://antfu.me/posts/why-reproductions-are-required-zh) 是最好的了。

**Comment by Ares-Chang** [comment]
link uni-app issues [#4350](https://github.com/dcloudio/uni-app/issues/4350#issuecomment-1623657138)

**Comment by Hbisedm** [comment]
> 

好的，我降版本就好了
