### ISSUE TITLE
Mac M1 芯片编译 App 报错

### ISSUE THREAD

**Issue by tong822218** [Ares-Chang/uni-vitesse#11]
我把项目用hbuildx打开，运行pnpm install 后  选择运行到app基座，然后报错
<img width="1045" alt="image" src="https://github.com/Ares-Chang/uni-vitesse/assets/9926531/dcc46c96-52d4-421f-a316-9f40696f797a">

**Comment by Ares-Chang** [comment]
请问可以再提供一此别的信息嘛，例如是否有修改，node/pnpm/hbuildx 版本等信息。
因为我没有真实安卓设备，选择了在夜神模拟器中运行是完全没有问题的。
![image](https://github.com/Ares-Chang/uni-vitesse/assets/36911513/d43fa9ac-aaac-4fb1-b8c6-cc4db1a29e20)

**Comment by tong822218** [comment]
感谢大佬这么快就回复了我，我详细说一下我这边遇到的问题，先说h5,我按照你提供的方法 npx degit xxxx  拉下代码后 运行pnpm instal  pnpm run dev:h5 这样是没有问题的，但是我把node_modues 和  pnpm_lock.yaml （你项目中自带的）删除后，重新pnpm install  & pnpm run dev:h5  就会报上面我截图的那个错误 。
app端，我用hbuild打开项目后 pnpm install  然后运行到 app底座直接就报上面的错误了，一模一样的   我的配置信息如下
<img width="359" alt="image" src="https://github.com/Ares-Chang/uni-vitesse/assets/9926531/d0e7fb80-cb77-4157-a846-9385079a0d13">
<img width="343" alt="image" src="https://github.com/Ares-Chang/uni-vitesse/assets/9926531/16a814e9-7cbf-4a12-9f9d-7416e98ddbec">
<img width="281" alt="image" src="https://github.com/Ares-Chang/uni-vitesse/assets/9926531/a301c63b-aef7-47e8-b742-986a614bfe73">

**Comment by Ares-Chang** [comment]
兄弟，你用的是新款 Mac 的芯片吧？
我找了一下，可以参考一下这个 [帖子](https://ask.dcloud.net.cn/question/145281) 看是否能解决你的问题。

**Comment by Ares-Chang** [comment]
我用的是 Win11 的环境，如果你删除了 pnpm-lock.yaml 文件重新下载的话，我不能确定它是否会按照你的系统来进行判断下载。

可以参考一下我[上面找的文章](https://ask.dcloud.net.cn/question/145281)，这是 Dcloud 的官方论坛，我看这个问题的热度还是很高的，但是官方好像并不想管。

可以试一下，我不是 Mac ，给不了你太大的帮助。

![image](https://github.com/Ares-Chang/uni-vitesse/assets/36911513/f721dee9-60d9-40f9-b1e2-a779bfe796e7)

**Comment by tong822218** [comment]
我这边试了一下还是不行，不过非常感谢你付出的时间 @Ares-Chang

**Comment by MrCat33** [comment]
嗨，我这边尝试复现您的问题，当我执行到您这个步骤的时候也会报错，但是与您是不同的错误信息
`把node_modues 和 pnpm_lock.yaml （你项目中自带的）删除后，重新pnpm install & pnpm run dev:h5`

![image](https://github.com/Ares-Chang/uni-vitesse/assets/24601590/0285fcd3-8435-4d76-884f-6aad6c00e3fb)

我猜测是与包的版本有联系，在不同的包版本之间造成不兼容的情况，所以我建议您尽量不要删除`pnpm_lock.yaml`这个文件

**Comment by tong822218** [comment]
感谢各位回复，我在项目中pnpm i @esbuild/darwin-x64@0.18.20 -D   安装完这个包后，可以在hbuildx app端正常启动了

**Comment by Ares-Chang** [comment]
👌那我就 close 了，有问题欢迎随时反馈~
