### ISSUE TITLE
h5端热更新时，全页刷新问题

### ISSUE THREAD

**Issue by Chilfish** [Ares-Chang/uni-vitesse#12]
你好，对于 #9 提及的不能热重载，即在 h5 端热重载时会导致全页强制刷新，我排查下来是 `@uni-helper/vite-plugin-uni-pages` 插件所导致的。目前该问题已经 [得以解决](https://github.com/uni-helper/vite-plugin-uni-pages/issues/95#event-9953930832)，实测只需要升级它到最新版本就行

**Comment by Ares-Chang** [comment]
Thanks ~ 非常感谢，依赖已更新，happy play!
