### ISSUE TITLE
现在这种情况如何使用第三方的UI框架和内置的组件

### ISSUE THREAD

**Issue by lzdml** [Ares-Chang/uni-vitesse#14]

**Comment by Ares-Chang** [comment]
正常使用组件库，如果库支持 npm 使用，直接 import 或者 easycom 使用都可以。主要看组件库是否支持。

这只是个脚手架，不直接影响业务逻辑

**Comment by Ares-Chang** [comment]
我尝试了 [uni-ui](https://github.com/dcloudio/uni-ui) 和 [ijry/uview-plus](https://github.com/ijry/uview-plus) 两个组件库，按照官方文档示例，通过 easycom 方式均显示成功。

easycom 可以在 pages.config.ts 文件中配置，详情可以参考 [@uni-helper/vite-plugin-uni-pages 文档](https://github.com/uni-helper/vite-plugin-uni-pages#readme)

![image](https://github.com/Ares-Chang/uni-vitesse/assets/36911513/5a2a48b5-bc13-46ca-b744-0eb9cef3fa9f)

![image](https://github.com/Ares-Chang/uni-vitesse/assets/36911513/0895508f-a277-4ebb-adf6-66e867bf5f86)

**Comment by lzdml** [comment]
好的, 感谢, 我再试一下
