### ISSUE TITLE
如果我想使用uni内置组件, zheng常使用的话就提示无用的标签

### ISSUE THREAD

**Issue by lzdml** [Ares-Chang/uni-vitesse#15]
<img width="892" alt="image" src="https://github.com/Ares-Chang/uni-vitesse/assets/137750167/cf81268d-9516-4d03-afdd-71c451d5a970">

**Comment by Ares-Chang** [comment]
error 提示无效的闭合标签，请检查是否有冗余闭合标签或者是否有标签未闭合。

推荐开启 eslint ，这是个好习惯。

如果检查没有问题，请把截图定位到报错提示代码行位置

**Comment by lzdml** [comment]
@Ares-Chang 
还有一个问题, 如果我想使用分享按钮, 正常来说只需要在按钮上添加 open-type="share"即可, 如何触发小程序的onShareAppMessage,或者小程序提供的其他事件呢
<img width="809" alt="image" src="https://github.com/Ares-Chang/uni-vitesse/assets/137750167/1ca90473-43a8-4be1-9412-92f2440bcda0">

**Comment by Ares-Chang** [comment]
此事件为 uniapp 提供支持，可以通过 `@dcloudio/uni-app` 进行引用。参考文档 [onshareappmessage](https://uniapp.dcloud.net.cn/api/plugins/share.html#onshareappmessage)

如果不了解 Composition API 使用方法可以参考 [组合式 API](https://uniapp.dcloud.net.cn/tutorial/vue3-composition-api.html) 使用方法

![image](https://github.com/Ares-Chang/uni-vitesse/assets/36911513/4d4fbd75-b433-4ea8-bda9-8beecb6a4f7e)
