### ISSUE TITLE
vscode-eslint2.4.2 无法启用 

### ISSUE THREAD

**Issue by light-huangli** [Ares-Chang/uni-vitesse#17]
使用该模板在vscode中vscode-eslint2.4.2中无法启用
[Error - 11:35:35] An unexpected error occurred:
[Error - 11:35:35] Error: Invalid Options:
- Unknown options: extensions
- 'extensions' has been removed.

**Comment by Ares-Chang** [comment]
我也遇到过，请检查 VSCode 全局用户配置，是不是设置了 eslint 的启用规则，如 `extensions`


![image](https://github.com/Ares-Chang/uni-vitesse/assets/36911513/705784bd-6b73-41ac-bba2-14110f64085c)

**Comment by Ares-Chang** [comment]
sorry，点错了。

`Ctrl + Shift + P` 搜索 `user settings` , 搜索一下 eslint 的 `extensions`，把对应配置删除就好了

**Comment by light-huangli** [comment]
方便给下全部的配置项吗

**Comment by Ares-Chang** [comment]
这是你自己的用户配置，你以前可以配置过 eslint 的全局规则，但现在配置被弃用了，你得从你自己配置里删除

**Comment by Ares-Chang** [comment]
看样子问题是解决了，如果有问题请再次开启此 issues
