### ISSUE TITLE
模版代码一丝不动直接运行小程序报错

### ISSUE THREAD

**Issue by sunpm** [Ares-Chang/uni-vitesse#18]
> 支付宝小程序
<img width="1644" alt="image" src="https://github.com/Ares-Chang/uni-vitesse/assets/35005831/3f1fb910-799c-41a9-b0a4-da50050e347f">

> 快手小程序
<img width="1280" alt="image" src="https://github.com/Ares-Chang/uni-vitesse/assets/35005831/89d042de-4968-4aaa-b0b3-06553661d2fe">

> 抖音小程序
<img width="1038" alt="image" src="https://github.com/Ares-Chang/uni-vitesse/assets/35005831/5a0a9520-3f6d-4adf-9e95-4a2ec5efca43">

**微信小程序运行是不报错的**
![image](https://github.com/Ares-Chang/uni-vitesse/assets/35005831/b925fe1b-ff1f-481e-ad18-69d9938b050d)

APP端安卓和ios模拟器都可以正常运行

我的开发环境如下：
OS: macOS Monterey，英特尔 I5
Node Version: v16.17.0
Package Manager: pnpm@8.11.0
Builder: vite

**Comment by Ares-Chang** [comment]
Sorry, 并没有尝试过除微信小程序外的其它平台，我去下几个平台尝试一下，之前没有过业务接触。

看你的这几个截图并不能确定是哪个或哪几个包造成的，可能修复起来比较困难，

最近比较忙，可能不是很有精力搞这个，如果找到问题可以去对应仓库，提几个 pr/issues 搞几个成就🫡

Thanks

**Comment by sunpm** [comment]
> Sorry, 并没有尝试过除微信小程序外的其它平台，我去下几个平台尝试一下，之前没有过业务接触。
> 
> 看你的这几个截图并不能确定是哪个或哪几个包造成的，可能修复起来比较困难，
> 
> 最近比较忙，可能不是很有精力搞这个，如果找到问题可以去对应仓库，提几个 pr/issues 搞几个成就🫡
> 
> Thanks

谢谢您的付出，在插件市场看到支持的端都打勾，误认为全平台支持😯

**Comment by Ares-Chang** [comment]
😅是我想当然了，以为 uniapp 编辑过了就没啥了，毕竟只是 template 没有逻辑。

感谢指出问题。

**Comment by sunpm** [comment]
据我了解的，支付宝小程序对 uniapp 的 sdk 版本有限制，然后抖音小程序的 provide-inject 也不支持，不知道现在有没有修复，uniapp vue3 的坑还是挺多😮‍💨

**Comment by Ares-Chang** [comment]
我找到问题了，是 `unplugin-auto-import` 的 `vueTemplate` 配置导致的。移除掉就恢复正常了。

但现在我还没有很好的办法解决，这个配置还是挺重要的，可以直接在 `template` 中使用自动导入的变量。

**Comment by sunpm** [comment]
您组织不打算出一个插件吗🤣

**Comment by Ares-Chang** [comment]
我现在还不能确定具体问题及表像，我稍后会把问题及现象同步到 [vitesse-uni-app](https://github.com/uni-helper/vitesse-uni-app) 仓库。其实我也是个小菜鸡🤣，只是比较活跃一点。

最近大家好像都比较忙，不确定什么解决方案及什么时间。

感谢！

**Comment by sunpm** [comment]
谢谢您和您组织的付出，在 uniapp 这个恶心的框架上面开拓了一片净土

**Comment by Ares-Chang** [comment]
![006APoFYly8hiyhflkuisg306o06lmy1](https://github.com/Ares-Chang/uni-vitesse/assets/36911513/231d95a0-8b2f-4212-94bf-6e8cbecd8ffe)

万分抱歉，我看到上来就报错以为是编译出了问题，还在这一通找。

是我写错了，还没看报错信息😭。

`uni.onThemeChange` 方法不兼容多平台小程序，做一下条件编译就好了。

![image](https://github.com/Ares-Chang/uni-vitesse/assets/36911513/42217494-a3dd-469f-b7ed-50f0eb23b7e4)

抱歉，耽误时间了，有问题随时反馈。

感谢！

**Comment by sunpm** [comment]
感谢您
