### ISSUE TITLE
微信小程序编译

### ISSUE THREAD

**Issue by lzdml** [Ares-Chang/uni-vitesse#19]
编译成微信小程序是webview吗

![image](https://github.com/Ares-Chang/uni-vitesse/assets/137750167/a73d178a-72ed-4b64-a15a-ff6423262cf4)

**Comment by Ares-Chang** [comment]
是的呢~除 web 端都无法直接跳转页面，需要使用 webview 打开。

参考 webview 使用，可以跳转外部链接

https://github.com/Ares-Chang/uni-vitesse/blob/c60a31f070210967165d44b97a199815a53f50f5/src/pages/webview.vue#L1-L7

https://github.com/Ares-Chang/uni-vitesse/blob/c60a31f070210967165d44b97a199815a53f50f5/src/composables/useRouter.ts#L22-L28

https://github.com/Ares-Chang/uni-vitesse/blob/c60a31f070210967165d44b97a199815a53f50f5/src/composables/useRouter.ts#L169-L171

**Comment by lzdml** [comment]
@Ares-Chang 也就等于说是在小程序端只能有一个页面?配置路由什么没有任何作用吗

**Comment by Ares-Chang** [comment]
emmm，你是自怎么理解的。我觉得我文档写的应该还挺清楚的。

参考: https://github.com/Ares-Chang/uni-vitesse/tree/master/src/pages

模板用了 https://github.com/uni-helper/vite-plugin-uni-pages 生成约定式路由，不需要配置原 uniapp 的 pages.json，可以看看文档了解一下。

还有，回复消息不需要 @ ，看到我会回复的，感谢。

**Comment by Ares-Chang** [comment]
请问问题是否解决，如果解决我就关闭此 Issues 了，如果依旧有问题可以激活此 Issues。

Thanks
