### ISSUE TITLE
添加个uniCloud

### ISSUE THREAD

**Issue by lentg** [Ares-Chang/uni-vitesse#2]
添加个uniCloud

**Comment by Ares-Chang** [comment]
可能会添加，但是我没有用过 uniCloud，如果你急切需要，欢迎 PR

**Comment by lentg** [comment]
https://github.com/yang1206/uniapp-template 这个框手架也是基于Vitesse的，就可以直接在Hbuilder里的项目左键添加uniCloud，也可以在Hbuilder里直接运行项目，你这个不行，要用命令行运行。

**Comment by Ares-Chang** [comment]
Sorry，我一开始的本意是脱离 HBuilderX ，直接使用脚手架来开发的。这样可以保证我自己的环境统一。

并且我的业务并不需要 uniCloud ，所以并没有了解过相关功能。也许你说的左健添加是和 HBuilderX 强绑定的，这个需要再研究。但是得等我有时间了才可以开始。

如果你喜欢这个仓库并且愿意维护的话，可以考虑 PR 或者 Fork 一下自己维护。如果特别着急，可能得再找找有没有别的开源仓库支持你的需求。

Thanks

**Comment by lentg** [comment]
重启电脑后，可以添加unicloud了，也能直接在HbuilderX里运行了，谢谢

**Comment by Ares-Chang** [comment]
欢迎使用
