### ISSUE TITLE
编译为微信小程序插件报错

### ISSUE THREAD

**Issue by eamd-wq** [Ares-Chang/uni-vitesse#20]
"dev:mp-wx:plugin": "uni build -w -p mp-weixin --plugin --out-dir dist/dev/mp-weixin/plugin",
    "build:mp-wx:plugin": "uni build -p mp-weixin --plugin --out-dir dist/build/mp-weixin/plugin",
    
    这两条命令可以编译为小程序插件，但是编译后会输出app.wxss文件 并且每个页面的wxss都会引入app.wxss 问题就在这里
    
    微信现在有个bug 就是其他页面引入app.wxss就会报错 将app.wxss改名为a1.wxss则没有报错
    
    来此想寻求一个解决方案，是否可以将此模板输出的app.wxss改个其他的名字；在uniapp文档中也为找到相关配置（可能是我没找到）

在微信提的问题 有回复 但是很摆烂
https://developers.weixin.qq.com/community/minihome/doc/000cee3e934a30ecb02177a7267800

**Comment by Ares-Chang** [comment]
?这个问题应该和这个仓库没有关系吧，我只提供了一个 template 不负责具体业务。

我没有写过小程序插件，不了解相关知识，我可以尝试一下，但不能保证解决问题。

你可以提供一个 [最小实现 repo](https://areschang.top/demo-repo) ，以便我开始尝试，感谢。

**Comment by eamd-wq** [comment]
是的 和仓库没有关系 
我目前开发时使用小程序模式  打包为插件时全局替换app.wxss为其他文件名称 暂时规避了这个问题


你的模板很棒；期待你后边可以有Vue、React以及更多框架模板；或许可以和爱好者一起建立前端框架模板站点，以输出前端最前沿最规范开发体验最好的框架模板大全；

**Comment by Ares-Chang** [comment]
感谢使用，可以多关注 [antfu](http://github.com/antfu) Vue 轮子哥，本模板是根据 [vitesse-lite](https://github.com/antfu/vitesse-lite) 魔改而来。

有关 UniApp 的生态休验增加可以多多观注 [Uni Helper](https://github.com/uni-helper/)，组织致力增强 uni-app 系列产品的开发体验，里面有很多提示开发体验明显的插件。
