### ISSUE TITLE
项目中的vue版本为3.4, 在实际使用中使用defineModel，报错

### ISSUE THREAD

**Issue by webarn** [Ares-Chang/uni-vitesse#21]
<img width="503" alt="image" src="https://github.com/Ares-Chang/uni-vitesse/assets/23495159/04100624-f577-4938-9047-81f6ff622b8f">

**Comment by Ares-Chang** [comment]
uniapp 有内置 vue 版本，原则上只要它不升级，你升级到多少都不会有用的。

并且 uniapp 近期也没有升级的打算, [link](https://github.com/dcloudio/uni-app/issues/4686).

可以参考我 input 组件里的写法，或者实在想用，试试 Vue Macros 吧
