### ISSUE TITLE
Missing dep unplugin-vue-macros?

### ISSUE THREAD

**Issue by c1emon** [Ares-Chang/uni-vitesse#22]
tsconfig.json seems need `unplugin-vue-macros` because of `@vue-macros/reactivity-transform/macros-global`

**Comment by Ares-Chang** [comment]
Sorry, I didn't understand what you mean.

`@vue-macros/reactivity-transform` plug-in package should already be in https://github.com/Ares-Chang/uni-vitesse/commit/57e6e3a4aa6b08fadbe1b9835fb1d562efabd6fd#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L78 been removed

If you still need it, you can try to install it yourself in the project

**Comment by c1emon** [comment]
vscode can't find `@vue-macros/reactivity-transform/macros-global`, so i installed `unplugin-vue-macros` which make vscode no more complaints. I think maybe it's something wrong with my env or project....Finally, thank you!
