### ISSUE TITLE
H5环境下面报错

### ISSUE THREAD

**Issue by TyCoding** [Ares-Chang/uni-vitesse#23]
简单的一个路由跳转都报错
useRouter.ts:142 Cannot read properties of undefined (reading 'replace')
TypeError: Cannot read properties of undefined (reading 'replace')

**Comment by Ares-Chang** [comment]
请提供，[最小复现 Demo](https://areschang.top/demo-repo)，以便我排查

无法复现问题，代码拉下来就能跑，H5 中并没有复现出你的问题。
