### ISSUE TITLE
button、view等标签红色提示

### ISSUE THREAD

**Issue by gao-xiang** [Ares-Chang/uni-vitesse#25]
![QQ截图20240501153400](https://github.com/Ares-Chang/uni-vitesse/assets/10647927/7decf246-71b2-43cb-87ff-b67ec85a72fe)

tsconfig.json

17行："@vue-macros/reactivity-transform/macros-global"好像是遗留。

**Comment by Ares-Chang** [comment]
请提供报错信息，

遗留配置已移除，thanks

**Comment by gao-xiang** [comment]
vueCompilerOptions 中添加以下后内容。 
 "plugins": [
      "@uni-helper/uni-app-types/volar-plugin"
    ]
