### ISSUE TITLE
unocss 在微信小程序中把icon图片全变成灰色

### ISSUE THREAD

**Issue by gao-xiang** [Ares-Chang/uni-vitesse#26]
unocss-preset-weapp  改为这个合适

**Comment by Ares-Chang** [comment]
请提供错误信息和最小重现 Demo ,并没有理解你遇到的问题

**Comment by gao-xiang** [comment]
编辑到小程序后，所有UI中的icon小图标的颜色全部变成灰色

**Comment by Ares-Chang** [comment]
[「请提供最小重现」](https://areschang.top/demo-repo)，我无法复现你的问题

**Comment by gao-xiang** [comment]
![222222222](https://github.com/Ares-Chang/uni-vitesse/assets/10647927/b47814df-2cb2-481b-906d-2f4935c44216)

这是使用uniapp ui  和Wot Design Uni  的图标，在小程序中大小和颜色等不生效。

**Comment by gao-xiang** [comment]
![11111111](https://github.com/Ares-Chang/uni-vitesse/assets/10647927/c405ef96-a87a-40d7-a6f2-c1695b3d5c94)


这是替换unocss-preset-weapp后，在小程度中就可以正常显示了，

**Comment by Ares-Chang** [comment]
[「请提供最小重现」](https://areschang.top/demo-repo), Thanks!

**Comment by Ares-Chang** [comment]
![image](https://github.com/Ares-Chang/uni-vitesse/assets/36911513/1c76924d-2a8b-427f-ad15-fd206fd22c0f)

简单理解，unocss attributify 与 组件库 样式冲突，可以选择关闭 attributify 或者添加 [attributify 前缀](https://unocss.dev/presets/attributify#prefix)如 my-color-red, 

或者简单点，不使用这个组件，[unocss 与 iconfiy 搭配](https://unocss.dev/presets/icons)起来是非常上瘾的一种行为。非常推荐!
