### ISSUE TITLE
router error

### ISSUE THREAD

**Issue by lentg** [Ares-Chang/uni-vitesse#3]
![image](https://github.com/Ares-Chang/uni-vitesse/assets/198310/d4cd7a5d-83f6-45e4-80ff-3f322d4febf4)

**Comment by Ares-Chang** [comment]
你把代码都拉全了嘛，这个应该是今天新写的，应该有个 router.ts 文件
![image](https://github.com/Ares-Chang/uni-vitesse/assets/36911513/b88aaf93-aaba-466a-8ff6-f27e229a1d95)

我这里没有复现问题，如果还是有问题的话，最好提供一个 demo repo 或者在线编辑器，有时间我看看。

**Comment by lentg** [comment]
是全新下载的，pnpm i后，直接运行，再建议兼容一下uni_modules 插件安装

**Comment by Ares-Chang** [comment]
欢迎使用，如果对你有帮助，请帮我点个 star

**Comment by Ares-Chang** [comment]
uni_modules 可以在 HBuilderX 中直接导入，并符合官网介绍的使用场景。
![image](https://github.com/Ares-Chang/uni-vitesse/assets/36911513/776894d4-2126-472f-ad7b-4c72badb7dd3)
![image](https://github.com/Ares-Chang/uni-vitesse/assets/36911513/7ae5979e-3270-4501-a3cf-cf3f23e9120e)

个人并不常用 uni_modules ，如果可以推荐使用 npm 安装。毕竟一开始的初衷是脱离 HBuilderX 的，这个功能和 HBuilderX 绑定非常强
