### ISSUE TITLE
如何生成APP wgt 包？

### ISSUE THREAD

**Issue by kkks2024** [Ares-Chang/uni-vitesse#34]
![image](https://github.com/user-attachments/assets/8f5d7bdd-28b4-4fee-8428-e9d12e54d6b5)

**Comment by Ares-Chang** [comment]
Sorry，这个和本仓库应该没有关系，这应该是 HBuilderX 本身提供的功能。

我没有用过，看了下 wgt 应该是他们要做的热更新内容吧，业务不相关没深度了解过，无法帮你解决疑问。

如果有什么想要分享的技术或文章可以持续留言，感谢使用。
