### ISSUE TITLE
执行pnpm dev:* 报错

### ISSUE THREAD

**Issue by cnelf** [Ares-Chang/uni-vitesse#4]
<img width="1511" alt="image" src="https://github.com/Ares-Chang/uni-vitesse/assets/42031617/49ff16b9-c794-49c7-a584-5eed5c10247b">

node version: v16.18.0

**Comment by cnelf** [comment]
应该是我本地的 pnpm 版本过低导致的，执行  `npx pnpm install` 之后可以解决

**Comment by Ares-Chang** [comment]
不，你应该是升级了 pinia 版本，最好先维持 `pinia@2.0.36`，升级后导致引用报错，我暂时还没有解决方法。

![image](https://github.com/Ares-Chang/uni-vitesse/assets/36911513/b320c875-4440-46ec-bb99-cf56c5cf9590)
