### ISSUE TITLE
Hello， 我遇到了一个问题 vite-plugin-uni-layouts 不生效

### ISSUE THREAD

**Issue by sharebravery** [Ares-Chang/uni-vitesse#5]
"@uni-helper/vite-plugin-uni-layouts": "^0.1.1",
    "@uni-helper/vite-plugin-uni-pages": "^0.2.2",
    "vue": "^3.3.4",
    "vite": "4.1.4",

**Comment by Ares-Chang** [comment]
你好，你的 package version 与示例文件并没有不一样，效果参考 [主页示例 web](https://uni-vitesse.netlify.app/#/)。

如果你重装依赖并重启项目后依旧有问题，请提示一个 demo repo 否则我无法准确复现你的问题，感谢。

[请提供最小重现](https://antfu.me/posts/why-reproductions-are-required-zh)

**Comment by sharebravery** [comment]
我刚才发现了问题 我在<route lang="yaml"> </route> 加入了基本信息之外的信息 导致它运行不正确 令我困惑的是即便我撤销了更改也不生效了 我去问一下这个库的吧

**Comment by Ares-Chang** [comment]
这个插件其实还没有热更新，你修改后需要重启项目.

你的 layout 没有正确加载，应该不是这个问题导致的，我按你説的修改了配置，但是依旧没有问题。

![image](https://github.com/Ares-Chang/uni-vitesse/assets/36911513/bc473b43-8d9b-4ce7-9247-474110a396d6)
![image](https://github.com/Ares-Chang/uni-vitesse/assets/36911513/200482cb-9df2-4f43-91cd-d8199785e3ea)

如果你想让我了解更多的话，请务必提供一个 demo repo ，或在线编辑器链接，因为我无法模拟出你遇见的问题，感谢。

**Comment by sharebravery** [comment]
找到问题了 吐血! 居然是头部注释的问题!
```
<!--
 * @Description: 头部不能有这个注释。。。
 * @Author:
 * @Date: 2023-06-30 09:05:38
-->
```


我本来还以为是我加上对tabbar的处理造成的 一直找一直找 o(╥﹏╥)o
```
    UniPages({
      dir: 'src/pages',
      routeBlockLang: 'yaml',
      exclude: ['**/components/*.vue'],
      subPackages: [
        'src/pages-sub',
      ],
      onBeforeWriteFile(ctx) {
        type PageMeta = (PageMetaDatum & { name: string; tabBar?: { text?: string; iconPath: string; selectedIconPath: string } })

        const pageMetaData = ctx.pageMetaData as PageMeta[]

        ctx.pagesGlobConfig!.tabBar!.list = pageMetaData.flatMap(e => 'tabBar' in e
          ? {
              pagePath: e.path,
              text: e.tabBar?.text ? e.tabBar.text : e.style?.navigationBarTitleText,
              iconPath: e.tabBar!.iconPath,
              selectedIconPath: e.tabBar!.selectedIconPath,
            }
          : [])
      },
    }),
```

**Comment by Ares-Chang** [comment]
... 这种东西见仁见智，我是并不推荐文件头部注释的，没什么用，而且时间作者，你改代码也并一一定记得会改。

不如做好 git commit ，推荐在 VSCode 中安装个插件更实用。

[GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)

![image](https://github.com/Ares-Chang/uni-vitesse/assets/36911513/03e4826d-149c-4646-8268-332e6f0390a2)

可以参考一下我的 [use](https://github.com/ares-chang/use) 里面用很多我觉得实用的插件。
