### ISSUE TITLE
构建后，打开小程序中间loading很久才出现页面，白屏时间太久

### ISSUE THREAD

**Issue by Yxliam** [Ares-Chang/uni-vitesse#7]

**Comment by Ares-Chang** [comment]
还好吧，只有在首次加载的时候可能加载比较长时间。我对比了一下官方的 cli ，热更新的时候还是可以的。

主要**可能**因为需要通过 `vite-plugin-uni-pages` 和 `vite-plugin-uni-layouts` 编译一下，其它插件应该还好。主要是它俩需要编译所有的页面文件再加工。

我对加载这块不是很了解，可能得优化一下。
