### ISSUE TITLE
不能热更新怎么破

### ISSUE THREAD

**Issue by BWrong** [Ares-Chang/uni-vitesse#9]

**Comment by Ares-Chang** [comment]
新增页面后重启一下项目，layout 暂时无法热更新。如果你对这块比较熟悉，可以查看这个插件 [`@uni-helper/vite-plugin-uni-layouts`](https://github.com/uni-helper/vite-plugin-uni-layouts) ，给它提个 PR。感谢

**Comment by BWrong** [comment]
暂时去掉了layout和pages 正常了

**Comment by Ares-Chang** [comment]
是的，这个地方没热更新😅，但是我觉得这两个或者 pages 是核心。

但是我技术有限，对热更新不是很了解无法更改。

**Comment by Ares-Chang** [comment]
如果感兴趣可以给它提个 pr 或者看看 [uni-helper](https://github.com/uni-helper) 的其它插件，都是针对 uni-app 开发的，如果能对你的项目起到帮助肯定是非常好的。

**Comment by BWrong** [comment]
后面空了在研究研究，忙着搬砖还没时间搞😀

**Comment by Ares-Chang** [comment]
感谢使用，如果有其它建议，欢迎 issues
